site_name: Microservices Bootcamp
site_description: A comprehensive guide to mastering microservices architecture.
theme:
  name: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Part 1 – Foundations:
      - Introduction: part1/README.md
      # - Core Principles of Microservices: part1/1.2-Core-Principles-of-Microservices.md
      - Designing Microservices: part1/1.3-Designing-Microservices.md
  # - Part 2 – Integration & Deployment:
  #     - Integration: part2/integration.md
  #     - Deployment: part2/deployment.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight

