site_name: Microservices Bootcamp
site_description: A comprehensive guide to mastering microservices architecture.
theme:
  name: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Part 1 – Foundations:
      - Introduction: part1/1.1-Introduction.md
      - Core Principles of Microservices: part1/1.2-Core-Principles-of-Microservices.md
      - Designing Microservices: part1/1.3-Designing-Microservices.md
      - Communication Patterns: part1/1.4-Communication-Patterns.md
      - Service Contracts: part1/1.4-Service-Contracts.md
  - Part 2 – Building Microservices:
      - Building Microservice: part2/2.1-Building-Microservice.md
      - Business Case: part2/2.2-Business-Case.md
      - Building First Microservice: part2/2.3-Building-First-Microservice-Lab-01.md
      - Adding Microservice: part2/2.4-Adding-Microservice-Lab-02.md
      - Creating Microservice with grpc: part2/2.5-Creating-Microservice-Via-grpc-Lab-03.md
      - Asynchronous Communication between Microservices: part2/2.6-Adding-Asynchronous-Communication-Lab-04.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight

