// <auto-generated />
using System;
using EvenTicket.Services.Discount.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvenTicket.Services.Discount.Migrations.DiscountDb;

[DbContext(typeof(DiscountDbContext))]
[Migration("20250701124022_Init")]
partial class Init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EvenTicket.Services.Discount.Entities.Coupon", b =>
            {
                b.Property<Guid>("CouponId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("AlreadyUsed")
                    .HasColumnType("bit");

                b.Property<int>("Amount")
                    .HasColumnType("int");

                b.Property<string>("Code")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CouponId");

                b.ToTable("Coupons");

                b.HasData(
                    new
                    {
                        CouponId = new Guid("140b49de-a914-435b-980f-ca0187d1733f"),
                        AlreadyUsed = false,
                        Amount = 10,
                        Code = "BeNice"
                    },
                    new
                    {
                        CouponId = new Guid("c1e882f4-6379-4cf3-a617-106729662c27"),
                        AlreadyUsed = false,
                        Amount = 20,
                        Code = "Awesome"
                    },
                    new
                    {
                        CouponId = new Guid("a42b824b-f719-4f3e-a894-1026fa0560d7"),
                        AlreadyUsed = false,
                        Amount = 100,
                        Code = "AlmostFree"
                    });
            });
#pragma warning restore 612, 618
    }
}