// <auto-generated />
using System;
using EvenTicket.Services.EventCatalog.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvenTicket.Services.EventCatalog.Migrations.EventCatalogDb
{
    [DbContext(typeof(EventCatalogDbContext))]
    partial class EventCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvenTicket.Services.EventCatalog.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("68ffabe5-d4bb-408d-88d8-39f4120bc9e4"),
                            Name = "Concerts"
                        },
                        new
                        {
                            CategoryId = new Guid("3f2373fa-525b-4118-9cde-c99f8d5a1d38"),
                            Name = "Musicals"
                        },
                        new
                        {
                            CategoryId = new Guid("1a58c498-f6fe-4a41-b1ec-bd2f33b1d2b2"),
                            Name = "Plays"
                        },
                        new
                        {
                            CategoryId = new Guid("373e11ef-4711-4f07-950b-b3aec7b39565"),
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("EvenTicket.Services.EventCatalog.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("EventId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = new Guid("e34a9568-52a2-4b6c-85ea-a5463124cd30"),
                            Artist = "Arijit Singh",
                            CategoryId = new Guid("68ffabe5-d4bb-408d-88d8-39f4120bc9e4"),
                            Date = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join India's most beloved playback singer Arijit Singh for his farewell tour across 15 Indian cities. Experience the magic of his soulful voice live.",
                            ImageUrl = "/img/arijit.jpg",
                            Name = "Arijit Singh Live in Concert",
                            Price = 5400
                        },
                        new
                        {
                            EventId = new Guid("f14b62ec-376c-43c8-bb53-a3cb167f16a2"),
                            Artist = "Kapil Sharma",
                            CategoryId = new Guid("68ffabe5-d4bb-408d-88d8-39f4120bc9e4"),
                            Date = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "India's comedy king Kapil Sharma brings his hilarious team for a live show that will leave you in splits. Featuring Sunil Grover, Krushna Abhishek and other special guests!",
                            ImageUrl = "/img/kapil.jpg",
                            Name = "Comedy Night with Kapil Sharma",
                            Price = 5500
                        },
                        new
                        {
                            EventId = new Guid("7ee7bfee-bdb3-4c46-90d3-57293f08f366"),
                            Artist = "Shankar Mahadevan",
                            CategoryId = new Guid("3f2373fa-525b-4118-9cde-c99f8d5a1d38"),
                            Date = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Experience this spectacular musical journey through India's history, composed by Shankar Mahadevan. The show has received rave reviews from critics and audiences alike.",
                            ImageUrl = "/img/desi-musical.jpg",
                            Name = "Bharat: The Great Indian Musical",
                            Price = 10000
                        },
                        new
                        {
                            EventId = new Guid("730f67eb-7ef9-4d90-b16d-1cfc381cf20d"),
                            Artist = "Pt. Birju Maharaj Troupe",
                            CategoryId = new Guid("3f2373fa-525b-4118-9cde-c99f8d5a1d38"),
                            Date = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kathak adaptation of the great epic featuring 100+ artists. Directed by Kathak legend Pt. Birju Maharaj.",
                            ImageUrl = "/img/mahabharata-musical.jpg",
                            Name = "Mahabharata: The Eternal Epic",
                            Price = 8500
                        });
                });

            modelBuilder.Entity("EvenTicket.Services.EventCatalog.Entities.Event", b =>
                {
                    b.HasOne("EvenTicket.Services.EventCatalog.Entities.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EvenTicket.Services.EventCatalog.Entities.Category", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
