@EvenTicket.Gateways.WebAPI_HostAddress = https://localhost:5056
@categoryId = 68ffabe5-d4bb-408d-88d8-39f4120bc9e4
@eventId = e34a9568-52a2-4b6c-85ea-a5463124cd30

### Get all categories
GET {{EvenTicket.Gateways.WebAPI_HostAddress}}/eventcatalog/api/Category/
Accept: application/json

###

### Get all events (optionally filter by categoryId)
GET {{EvenTicket.Gateways.WebAPI_HostAddress}}/eventcatalog/api/Event?categoryId={{categoryId}}
Accept: application/json

###

### Get event by eventId
GET {{EvenTicket.Gateways.WebAPI_HostAddress}}/eventcatalog/api/Event/{{eventId}}
Accept: application/json

###
