name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write 

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force


      # - name: Deploy docs
      #   uses: https://github.com/Amitpnk/microservices-bootcamp@main
      #   # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.gh-page-token }}
      #    # CUSTOM_DOMAIN: optionaldomain.com
      #     CONFIG_FILE: mkdocs.yml
      #     EXTRA_PACKAGES: build-base
      #     # GITHUB_DOMAIN: github.myenterprise.com
      #     REQUIREMENTS: requirements.txt
